import '@config/styles/index.css';
import '@config/styles/global.scss';

import Header from '@widgets/header';
import ScrollIndicator from '@widgets/indicator';

export const metadata = {
   title: 'burmister',
   description: 'Generated by create next app',
};

export const viewport = {
   width: 'device-width',
   initialScale: 1,
   maximumScale: 1,
   userScalable: false,
};

export default function RootLayout({ children }) {
   return (
      <html lang="ru">
         <body>
            <Header />
            {/* <ScrollIndicator /> */}
            <main>{children}</main>
         </body>
      </html>
   );
}
